In [59]:
import sys
import matplotlib
#matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
import librosa
import pywt
import sounddevice as sd

In [60]:
#load the apropriate file
zfile=np.load(r"C:\Users\Thanasis\Documents\DSP\DSP20_LAB2\step_00.npz")

#loading first;s file parametrs
xacc=np.zeros(len(zfile['acc']))
yacc=np.zeros(len(zfile['acc']))
zacc=np.zeros(len(zfile['acc']))

w=len(zfile['acc'])
for i in range(w):
        xacc[i]=zfile['acc'][i][0]
        yacc[i]=zfile['acc'][i][1]
        zacc[i]=zfile['acc'][i][2]
#pass the in variables for easier use
#xacc=zfile['acc'][:][0]
#yacc=zfile['acc'][:][1]
#zacc=zfile['acc'][:][2]


In [61]:
#Creating subplot objects
fig, (ax1,ax2,ax3) = plt.subplots(nrows=3,ncols=1)
ax1.grid(True)
ax2.grid(True)
ax3.grid(True)
ax1.set_ylabel("dimension x-accelarometer",rotation=80)
ax2.set_ylabel("dimension y-accelarometer",rotation=80)
ax3.set_ylabel("dimension z-accelarometer",rotation=80)
ax1.set_title("Accelarometer Data")
ax1.plot(xacc,label='xacc',color='green')
ax2.plot(yacc,label='yacc',color='blue')
ax3.plot(zacc,label='zacc',color='red')
plt.tight_layout()
#for use in terminal save figure
#plt.savefig(zfile.files[0] + ".png" , bbox_inches="tight")
plt.show()

In [62]:
plt.title("Accelarometer Data")
plt.ylabel("dimension x-accelarometer",rotation=90)
plt.plot(xacc,label='xacc',color='green')
#plt.savefig(zfile.files[0]+ "dimension x-accelarometer" + ".png" , bbox_inches="tight")
#plt.clf()
plt.show()

plt.title("Accelarometer Data")
plt.ylabel("dimension y-accelarometer",rotation=90)
plt.plot(yacc,label='yacc',color='blue')
#plt.savefig(zfile.files[0]+"dimension y-accelarometer" + ".png" , bbox_inches="tight")
#plt.clf()
plt.show()

plt.title("Accelarometer Data")
plt.ylabel("dimension z-accelarometer",rotation=90)
plt.plot(zacc,label='zacc',color='red')
plt.show()
#plt.savefig(zfile.files[0] +"dimension z-accelarometer"+ ".png" , bbox_inches="tight")

In [63]:
xgyr=np.zeros(len(zfile['gyr']))
ygyr=np.zeros(len(zfile['gyr']))
zgyr=np.zeros(len(zfile['gyr']))
hrm=np.zeros(len(zfile['hrm']))
e=len(zfile['gyr'])
for i in range(e):
        xgyr[i]=zfile['gyr'][i][0]
        ygyr[i]=zfile['gyr'][i][1]
        zgyr[i]=zfile['gyr'][i][2]
s=len(zfile['hrm'])
for i in range(s):
        hrm[i]=zfile['hrm'][i]

In [64]:
fig1, (ax4,ax5,ax6) = plt.subplots(nrows=3,ncols=1)
ax4.grid(True)
ax5.grid(True)
ax6.grid(True)
ax4.set_ylabel("dimension x-gyroscope",rotation=80)
ax5.set_ylabel("dimension y-gyroscope",rotation=80)
ax6.set_ylabel("dimension z-gyroscope",rotation=80)
ax4.set_title("Gyroscope Data")
ax4.plot(xgyr,label='xgyr',color='green')
ax5.plot(ygyr,label='ygyr',color='blue')
ax6.plot(zgyr,label='zgyr',color='red')
plt.tight_layout()
#plt.savefig(zfile.files[1] + ".png" , bbox_inches="tight")
plt.show()
#plt.clf()
plt.title("Gyroscope  Data")
plt.ylabel("dimension x-gyroscope",rotation=90)
plt.plot(xgyr,label='xgyr',color='green')
#plt.savefig(zfile.files[1]+"dimension x-gyroscope" + ".png" , bbox_inches="tight")
plt.show()
#plt.clf()
plt.title("Gyroscope Data")
plt.ylabel("dimension y-gyroscope",rotation=90)
plt.plot(ygyr,label='ygyr',color='blue')
#plt.savefig(zfile.files[1]+"dimension y-gyroscope" + ".png" , bbox_inches="tight")
plt.show()
#plt.clf()
plt.title("Gyroscope Data")
plt.ylabel("dimension z-gyroscope",rotation=90)
plt.plot(zgyr,label='zgyr',color='red')
plt.show()
#plt.savefig(zfile.files[1] +"dimension z-gyroscope"+ ".png" , bbox_inches="tight")

#plt.clf()
plt.title("Heartbeat Data")
plt.ylabel("hrm",rotation=90)
plt.plot(hrm,label='hrm',color='red')

#plt.savefig(zfile.files[2] + ".png" , bbox_inches="tight")
plt.show()

In [128]:
#1.2
def ste(x, window='hamming', window_length=400):
    if isinstance(window, str):#npt nessesarilly needs, it narrows the possible windows to be created
        window = sp.signal.get_window(window, window_length)#garuntees to make the window string, no tuple 
    
    return sp.signal.convolve(x**2, window, mode="same")#type length of max(x,window) in samples

In [129]:
fs=20 #sampling freq acc,gyr
fsh=5 #sampling freq hrm

def plotter(signal,fs,name="STE signal",window='hamming',time=20):
    stesig=ste(signal,window, time*fs)
    #
    sec=np.linspace(0,len(stesig),len(stesig))/fs
    plt.plot(sec,stesig)
    p=str(name)
    plt.title(p)
    plt.xlabel("Sec")
    plt.show()
    return sec,stesig
plotter(xacc,fs)
def plotterbulk(signal,freq,title="Signal and its STE"):
    #
    sec,stesig=plotter(signal,fs=freq,name="STE signal",window='hamming',time=20)
    fig, ax7 = plt.subplots()

    ax7.set_xlabel('Sec')
    ax7.set_ylabel('Input signal', color='red')
    ax7.plot(sec, signal, color='red')
    ax7.tick_params(axis='y')
    #
    ax8 = ax7.twinx()  # instantiate a second axes that shares the same x-axis

    ax8.set_ylabel('ste', color='blue')  # we already handled the x-label with ax1
    ax8.plot(sec, stesig, color='blue')
    ax8.tick_params(axis='y')

    fig.tight_layout()  # otherwise the right y-label is slightly clipped
    p=str(title)
    plt.title(p)
    plt.show()
plotterbulk(xacc,fs)
plotterbulk(xgyr,fs)
plotterbulk(hrm,fsh)



"""
stexgyr=ste(xgyr,'hamming', 400)
stexhrm=ste(hrm,'hamming', 100)    
sech=np.linspace(0,len(stexhrm),len(stexhrm))/fsh
plt.plot(sec,stexacc)
plt.title("STE xgyr")
plt.xlabel("Sec")
plt.show()
plt.plot(sech,stexhrm)
plt.title("STE xhrm")
plt.xlabel("Sec")
plt.show()
"""

'\nstexgyr=ste(xgyr,\'hamming\', 400)\nstexhrm=ste(hrm,\'hamming\', 100)    \nsech=np.linspace(0,len(stexhrm),len(stexhrm))/fsh\nplt.plot(sec,stexacc)\nplt.title("STE xgyr")\nplt.xlabel("Sec")\nplt.show()\nplt.plot(sech,stexhrm)\nplt.title("STE xhrm")\nplt.xlabel("Sec")\nplt.show()\n'

In [130]:
from __future__ import division
#1.3
def plotterbeauty(signal,fs,signame,time=20):
    hl=int((time/2)*fs)
    stftacc=librosa.stft(signal,n_fft=1024,hop_length=hl,win_length=int(fs*time))#stft window length 40 samples overlappng 20 samples 50%
    #
    sec=np.linspace(0,int(len(signal)/fs),round(len(signal)/(fs*time/2)))
    #
    freq= np.linspace(0,10,np.shape(stftacc)[0])
    
    plt.pcolormesh(sec,freq,np.log(np.abs(stftacc)))
    python_power=str(signame)
    plt.title('spectrogram of log('+python_power+') stft ')
    plt.xlabel('Sec')
    plt.ylabel('Freq')
    plt.show()
plotterbeauty(xacc,fs,"x[n]")
plotterbeauty(hrm,fsh,"hrm[n]")


In [146]:
#1.4
stfile=np.load(r"C:\Users\Thanasis\Documents\DSP\DSP20_LAB2\sleep_03.npz")
slfile=np.load(r"C:\Users\Thanasis\Documents\DSP\DSP20_LAB2\step_03.npz")

slxacc=slfile['acc'][:,0]
slyacc=slfile['acc'][:,1]
slzacc=slfile['acc'][:,2]
slxgyr=slfile['gyr'][:,0]
slygyr=slfile['gyr'][:,1]
slzgyr=slfile['gyr'][:,2]
slhrm=slfile['hrm']
fslfile=[]
fslfile.append(slxacc)
fslfile.append(slyacc)
fslfile.append(slzacc)
fslfile.append(slxgyr)
fslfile.append(slygyr)
fslfile.append(slzgyr)
#fslfile.append(slhrm)
Eslxacc=ste(slxacc)
Eslyacc=ste(slyacc)
Eslzacc=ste(slzacc)
Eslxgyr=ste(slxgyr)
Eslygyr=ste(slygyr)
Eslzgyr=ste(slzgyr)
Eslhrm=ste(slhrm,window_length=100)
def array(sig):
    values=np.zeros(4)
    values[0]=np.mean(ste(sig,window_length=w))
    values[1]=np.min(ste(sig,window_length=w))
    values[2]=np.max(ste(sig,window_length=w))
    values[3]=np.std(ste(sig,window_length=w))
    return values
print("mean","min","max","std",sep='                ')
print(*(array(sig) for sig in fslfile),sep='\n')
print(array(slhrm))


mean                min                max                std
[28894.44565445 11044.28404803 37552.10787593  7516.69876743]
[19926.71371378  8097.35097359 26433.43369156  5349.31721907]
[17251.1552117   6292.06467817 24206.04753262  5442.56334901]
[30113555.92122731  8344189.40924766 43834414.39935677 10861744.41825299]
[5467920.78236709 2507062.55733444 7328730.30658521 1477444.21936722]
[6092096.5026433  2419801.37087509 8697777.25312547 1976123.92812309]
[1.64875132e+09 1.49212333e+09 1.72396951e+09 6.65866818e+07]


In [150]:
stxacc=stfile['acc'][:,0]
styacc=stfile['acc'][:,1]
stzacc=stfile['acc'][:,2]
stxgyr=stfile['gyr'][:,0]
stygyr=stfile['gyr'][:,1]
stzgyr=stfile['gyr'][:,2]
sthrm=stfile['hrm']
st=[]
st.append(stxacc)
st.append(styacc)
st.append(stzacc)
st.append(stxgyr)
st.append(stygyr)
st.append(stzgyr)

Εstxacc=ste(stxacc)
Εstyacc=ste(stxacc)
Εstzacc=ste(stxacc)
Εstxgyr=ste(stxgyr)
Εstygyr=ste(stxgyr)
Εstzgyr=ste(stxgyr)
Εsthrm=ste(sthrm,window_length=100)
print("  mean","min","max","std",sep='           ')
print(*(array(sig) for sig in st),sep='\n')
print(array(slhrm))

  mean           min           max           std
[ 90.89502453  22.06190845 155.73017532  46.63801066]
[32.8910221  13.47735493 44.56510227  9.07067557]
[ 98.17983573  19.4997262  166.6811609   51.68110663]
[37613.70059523 12929.78326862 55691.07789138 13569.72674535]
[2996.22808974  895.71672606 4365.85848767 1063.11723354]
[3397.41329612  502.51894386 5259.91382715 1555.94701427]
[1.64875132e+09 1.49212333e+09 1.72396951e+09 6.65866818e+07]
